// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8caQ7gGGEYOAAdeibDtSx8gzH_qOf4g',
    appId: '1:644438329073:web:327588e1efbe06fac0cb50',
    messagingSenderId: '644438329073',
    projectId: 'home-75c32',
    authDomain: 'home-75c32.firebaseapp.com',
    storageBucket: 'home-75c32.firebasestorage.app',
    measurementId: 'G-45HSPHTNWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDRWEWfN787BbWC67SKSfvodndkdHCWVs',
    appId: '1:644438329073:android:82175e79fbfffc34c0cb50',
    messagingSenderId: '644438329073',
    projectId: 'home-75c32',
    storageBucket: 'home-75c32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7k_HtHax8U8xMUIHo74dhHUluPFCkTg',
    appId: '1:644438329073:ios:c61d8519848a5ed7c0cb50',
    messagingSenderId: '644438329073',
    projectId: 'home-75c32',
    storageBucket: 'home-75c32.firebasestorage.app',
    iosBundleId: 'com.example.glaziaHomeSecureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7k_HtHax8U8xMUIHo74dhHUluPFCkTg',
    appId: '1:644438329073:ios:c61d8519848a5ed7c0cb50',
    messagingSenderId: '644438329073',
    projectId: 'home-75c32',
    storageBucket: 'home-75c32.firebasestorage.app',
    iosBundleId: 'com.example.glaziaHomeSecureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8caQ7gGGEYOAAdeibDtSx8gzH_qOf4g',
    appId: '1:644438329073:web:3dc08bdda6bec1dec0cb50',
    messagingSenderId: '644438329073',
    projectId: 'home-75c32',
    authDomain: 'home-75c32.firebaseapp.com',
    storageBucket: 'home-75c32.firebasestorage.app',
    measurementId: 'G-S2887J89JJ',
  );
}
